name: Generate Datas

on:
  schedule:
    - cron: "0 */24 * * *" # execute every 24 hours
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - name: Generate Snake SVG
        uses: Platane/snk@v3.2.0
        id: snake-gif
        with:
          target_branch: main
          build_dir: dist
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg
